language: android
sudo: false
jdk: oraclejdk8
android:
  components:
  - build-tools-27.0.3
  - android-27
  - extra
script:
- "./gradlew test"
- "./gradlew lint"
- bash .travis/script.sh

before_install:
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
