language: android
sudo: required
jdk: oraclejdk8

env:
  global:
  - ANDROID_API=27
  - ANDROID_BUILD_TOOLS=27.0.3
  - EMULATOR_API_LEVEL=21

android:
  components:
  - android-$ANDROID_API
  - build-tools-$ANDROID_BUILD_TOOLS
  - extra
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL

  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
- "./gradlew test"
- "./gradlew lint"
- "./gradlew sonarqube \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.organization=remmeds \
             -Dsonar.login=71a0474c2d6a00ad268e14a1419ffd5ea04f720b"

#jobs:
#  include:
#    - stage: Unit Test
#      script:
#    - stage: Linter
#      script: ./gradlew lint
#    - stage: Sonarcloud Job
#      script: "./gradlew sonarqube \
#                  -Dsonar.host.url=https://sonarcloud.io \
#                  -Dsonar.organization=remmeds \
#                  -Dsonar.login=71a0474c2d6a00ad268e14a1419ffd5ea04f720b"

before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
- ./gradlew dependencies || true

before_script:
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
